# Generated by Django 3.0.5 on 2020-04-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_on_header', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.FloatField(default=0.0)),
                ('number_pieces', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_home_page', models.BooleanField(default=False)),
                ('promotion', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('is_sauce', models.BooleanField(default=False)),
                ('is_sour_sweet_sauce', models.BooleanField(default=False)),
                ('is_ginger_wasabi', models.BooleanField(default=False)),
                ('free_nos', models.IntegerField(default=0)),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'db_table': 'product_attributes',
            },
        ),
    ]
