# Generated by Django 3.0.5 on 2020-04-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200429_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='product_id',
            new_name='product',
        ),
    ]
